os:
  - linux
services:
  - docker
language: node_js
node_js:
  - 10.16.1
jdk:
  - oraclejdk8
cache:
  directories:
    - node
    - node_modules
    - '$HOME/.gradle'
env:
  global:
    - NODE_VERSION=10.16.1
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - NG_CLI_ANALYTICS="false"
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - nvm install $NODE_VERSION
  - npm install -g npm
  - node -v
  - npm -v
install:
  - npm install
script:
  - chmod +x gradlew
  - './gradlew clean test integrationTest'
  - './gradlew npm_run_test-ci -PnodeInstall --no-daemon'
  - './gradlew bootJar -Pprod -x test'
  - './gradlew deployHeroku'
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
deploy:
  provider: heroku
  api_key:
    secure: WsXd6wbRIsZrrP0deOUwx8wcViv7ondxrSNra0nxmPG5ztXUhkgO5Jr+BKOtzWjh5/RA4k56lmhSlDEsPjgaDaWKZYSq7In1x4S8skb+Q/BXRl7Qs7b0S4sacLpYDMiqsfT29ZfbnbwXxBMtfEhWK+mnly+gPCUSUxhp3VzU6uNiVJ9+N8hyJR1GjSfTA78xngRJAvCQh4n6yCFZo/jWMrsQYI5h/S8ZgcNOl9awitPxVpO3hiu2zs8gj2zZkufAX7lXI+/PDq/E9WWqyT+oGkC/AYdxBBjYQV86pqlCWxoWoE0eI1jvhtStLMQi8gmrBUwhgtnmYew5OkAXUC2VK9sPEQVSNgVWSTvaH7LG9Um8JpBAgH42Onz9e/tCxeUysa9Q1VfILAyg88r3369DifEQHKhfSKgRteW6d/960SjamOZ8eb/3XK5wl9zOW2gwcW+TdESTscBDEoyvmdoBmIpnNiHc0cbDLbD9RdR24AQ7VJ8oBHsIMTMHDr/78460wTRIQwjBMZqWVEY2wogphukx8kicRopVzPHPcSQT2wqvBul5d/MBt4jf1vC0E6ib/ig5/AFPPKJx3fwFGGOaI1mPtAjHvxp1OQ/1IgSMUHm6Bo/J5cMKNCchEtxYMg38zdlJFXQl9RENn3u5CarBJiFjOjYd+DAGW035WfKn0rE=
  app: salatracker
