os:
  - linux
services:
  - docker
language: node_js
node_js:
  - 10.16.1
jdk:
  - oraclejdk8
cache:
  directories:
    - node
    - node_modules
    - '$HOME/.gradle'
env:
  global:
    - NODE_VERSION=10.16.1
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - NG_CLI_ANALYTICS="false"
    - secure: WY7V8q9RD5t7Gjn5c777MQba8us3D8lnDyQvohE98NTmKNDCUyW7I8Hrnk/74HDMKrCiCchdHXEMqUXGnuqTAELrX1MZNx4HKCyO0Ylsv9rpSumoYsKoEuTRkD4hGoEgItTR4k6CaIOMINn7efZPHvyGqtgLm14iogRtMtsiRXuGi7ySBQL3EmQaXJUgMUMt83mcKFj8pRmoi+wXnCqL7ofwgTCObcuFNWJNSLZA8oBLGcGj9iQoTRgfAjymbX1uDlYV/RT4RYjbaHZB8CWhsnS4wglcNDDCStBwdroO31jFxMBOhcbsJVcajNaYPtFZfUWW7Cc0OdnpJLI38UbkENrHSFk6Hh92KWxLvZ84REYJ8+depxBYm6TURQrWnUIR56U65v/pEhmmxH/AyazNNqNVJZD1wFjlavJ4VPIFQmvNVXWOPfj7SLRcTgeUoz6wGDUSrYnTTmLIGW6fMRlDAxILJleljOGrYYQEk+IGl4mjWJp40cPdbbt6RY2LwLvQP95SROs/q3X5sMvdmme65vph36sWx45Ka5g717Q26HP1B/d3rGVm5ufB1Q8nC628Bigylccfdk4z1P58FWYEDZflKfu5uujSA7rRslc4BpraMpewtpIZv4D7q8ywCoTgyvG8ytq6J4a+x9roS9vb7/S1e+viJKuIgySj7UbSC8I=
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - nvm install $NODE_VERSION
  - npm install -g npm
  - node -v
  - npm -v
install:
  - npm install
script:
  - chmod +x gradlew
  - './gradlew clean test integrationTest'
  - './gradlew npm_run_test-ci -PnodeInstall --no-daemon'
  - './gradlew bootJar -Pprod -x test'
  - './gradlew deployHeroku'
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
